#!/bin/bash


while getopts c: option
do
	case "${option}"
    	in
          c) FILEPATH=${OPTARG};;
    esac
done

source ${FILEPATH}/phenstat.profile
export PATH=~/tex/2017/bin/x86_64-linux/:$PATH

# 
# Run the process with weight modelled in
# 
ARGS="${FILEPATH}/functionGenerateReport.R --file=$1 --result=${FILEPATH}/../result --mapfile=${FILEPATH}/functionMethodMap --withWeight=TRUE"
echo running: [Rscript ${ARGS}]
Rscript ${ARGS}

