
package org.mousephenotype.impress;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImpressSoapPort", targetNamespace = "http://www.mousephenotype.org/impress/soap/server")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImpressSoapPort {


    /**
     * @return string[] Pipeline keys
     * 
     * @return
     *     returns org.mousephenotype.impress.ArrayOfString
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getPipelineKeys")
    @WebResult(name = "getPipelineKeysResult", targetNamespace = "")
    @RequestWrapper(localName = "getPipelineKeys", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetPipelineKeys")
    @ResponseWrapper(localName = "getPipelineKeysResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetPipelineKeysResponse")
    public ArrayOfString getPipelineKeys();

    /**
     * @param string $procedureKey
     * 
     * @param procedureKey
     * @return
     *     returns org.mousephenotype.impress.ArrayOfString
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getProcedureKeys")
    @WebResult(name = "getParameterKeysResult", targetNamespace = "")
    @RequestWrapper(localName = "getProcedureKeys", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterKeys")
    @ResponseWrapper(localName = "getParameterKeysResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterKeysResponse")
    public ArrayOfString getParameterKeys(
        @WebParam(name = "procedureKey", targetNamespace = "")
        String procedureKey);

    /**
     * @param string $procedureKey
     * 
     * @param procedureKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getParameters")
    @WebResult(name = "getParametersResult", targetNamespace = "")
    @RequestWrapper(localName = "getParameters", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameters")
    @ResponseWrapper(localName = "getParametersResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParametersResponse")
    public Object getParameters(
        @WebParam(name = "procedureKey", targetNamespace = "")
        String procedureKey);

    /**
     * @param string $parameterKey
     * 
     * @param parameterKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getParameterOptions")
    @WebResult(name = "getParameterOptionsResult", targetNamespace = "")
    @RequestWrapper(localName = "getParameterOptions", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterOptions")
    @ResponseWrapper(localName = "getParameterOptionsResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterOptionsResponse")
    public Object getParameterOptions(
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $parameterKey
     * 
     * @param parameterKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getParameterIncrements")
    @WebResult(name = "getParameterIncrementsResult", targetNamespace = "")
    @RequestWrapper(localName = "getParameterIncrements", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterIncrements")
    @ResponseWrapper(localName = "getParameterIncrementsResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterIncrementsResponse")
    public Object getParameterIncrements(
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $parameterKey
     * 
     * @param parameterKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getParameterMPTerms")
    @WebResult(name = "getParameterMPTermsResult", targetNamespace = "")
    @RequestWrapper(localName = "getParameterMPTerms", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterMPTerms")
    @ResponseWrapper(localName = "getParameterMPTermsResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterMPTermsResponse")
    public Object getParameterMPTerms(
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $parameterKey
     * 
     * @param parameterKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getParameterEQTerms")
    @WebResult(name = "getParameterEQTermsResult", targetNamespace = "")
    @RequestWrapper(localName = "getParameterEQTerms", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterEQTerms")
    @ResponseWrapper(localName = "getParameterEQTermsResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterEQTermsResponse")
    public Object getParameterEQTerms(
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $parameterKey
     * 
     * @param parameterKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getParameterOntologyOptions")
    @WebResult(name = "getParameterOntologyOptionsResult", targetNamespace = "")
    @RequestWrapper(localName = "getParameterOntologyOptions", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterOntologyOptions")
    @ResponseWrapper(localName = "getParameterOntologyOptionsResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterOntologyOptionsResponse")
    public Object getParameterOntologyOptions(
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $pipelineKey
     * 
     * @param pipelineKey
     * @return
     *     returns org.mousephenotype.impress.ArrayOfString
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getProcedureKeys")
    @WebResult(name = "getProcedureKeysResult", targetNamespace = "")
    @RequestWrapper(localName = "getProcedureKeys", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetProcedureKeys")
    @ResponseWrapper(localName = "getProcedureKeysResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetProcedureKeysResponse")
    public ArrayOfString getProcedureKeys(
        @WebParam(name = "pipelineKey", targetNamespace = "")
        String pipelineKey);

    /**
     * @param string $pipelineKey
     * 
     * @param pipelineKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getProcedures")
    @WebResult(name = "getProceduresResult", targetNamespace = "")
    @RequestWrapper(localName = "getProcedures", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetProcedures")
    @ResponseWrapper(localName = "getProceduresResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetProceduresResponse")
    public Object getProcedures(
        @WebParam(name = "pipelineKey", targetNamespace = "")
        String pipelineKey);

    /**
     * @param string $pipelineKey
     * 
     * @param pipelineKey
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#isValidPipeline")
    @WebResult(name = "isValidPipelineResult", targetNamespace = "")
    @RequestWrapper(localName = "isValidPipeline", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.IsValidPipeline")
    @ResponseWrapper(localName = "isValidPipelineResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.IsValidPipelineResponse")
    public boolean isValidPipeline(
        @WebParam(name = "pipelineKey", targetNamespace = "")
        String pipelineKey);

    /**
     * @param string $procedureKey
     * 
     * @param procedureKey
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#isValidProcedure")
    @WebResult(name = "isValidProcedureResult", targetNamespace = "")
    @RequestWrapper(localName = "isValidProcedure", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.IsValidProcedure")
    @ResponseWrapper(localName = "isValidProcedureResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.IsValidProcedureResponse")
    public boolean isValidProcedure(
        @WebParam(name = "procedureKey", targetNamespace = "")
        String procedureKey);

    /**
     * @param string $parameterKey
     * 
     * @param parameterKey
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#isValidParameter")
    @WebResult(name = "isValidParameterResult", targetNamespace = "")
    @RequestWrapper(localName = "isValidParameter", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.IsValidParameter")
    @ResponseWrapper(localName = "isValidParameterResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.IsValidParameterResponse")
    public boolean isValidParameter(
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $pipelineKey
     * 
     * @param pipelineKey
     * @param procedureKey
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#pipelineHasProcedure")
    @WebResult(name = "pipelineHasProcedureResult", targetNamespace = "")
    @RequestWrapper(localName = "pipelineHasProcedure", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.PipelineHasProcedure")
    @ResponseWrapper(localName = "pipelineHasProcedureResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.PipelineHasProcedureResponse")
    public boolean pipelineHasProcedure(
        @WebParam(name = "pipelineKey", targetNamespace = "")
        String pipelineKey,
        @WebParam(name = "procedureKey", targetNamespace = "")
        String procedureKey);

    /**
     * @param string $procedureKey
     * 
     * @param parameterKey
     * @param procedureKey
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#procedureHasParameter")
    @WebResult(name = "procedureHasParameterResult", targetNamespace = "")
    @RequestWrapper(localName = "procedureHasParameter", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.ProcedureHasParameter")
    @ResponseWrapper(localName = "procedureHasParameterResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.ProcedureHasParameterResponse")
    public boolean procedureHasParameter(
        @WebParam(name = "procedureKey", targetNamespace = "")
        String procedureKey,
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $parameterKey
     * 
     * @param parameterKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getParameter")
    @WebResult(name = "getParameterResult", targetNamespace = "")
    @RequestWrapper(localName = "getParameter", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameter")
    @ResponseWrapper(localName = "getParameterResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetParameterResponse")
    public Object getParameter(
        @WebParam(name = "parameterKey", targetNamespace = "")
        String parameterKey);

    /**
     * @param string $procedureKey
     * 
     * @param pipelineKey
     * @param procedureKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getProcedure")
    @WebResult(name = "getProcedureResult", targetNamespace = "")
    @RequestWrapper(localName = "getProcedure", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetProcedure")
    @ResponseWrapper(localName = "getProcedureResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetProcedureResponse")
    public Object getProcedure(
        @WebParam(name = "procedureKey", targetNamespace = "")
        String procedureKey,
        @WebParam(name = "pipelineKey", targetNamespace = "")
        String pipelineKey);

    /**
     * @param string $pipelineKey
     * 
     * @param pipelineKey
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getPipeline")
    @WebResult(name = "getPipelineResult", targetNamespace = "")
    @RequestWrapper(localName = "getPipeline", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetPipeline")
    @ResponseWrapper(localName = "getPipelineResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetPipelineResponse")
    public Object getPipeline(
        @WebParam(name = "pipelineKey", targetNamespace = "")
        String pipelineKey);

    /**
     * @return string DateTime in W3C format
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.mousephenotype.org/impress/soap/server#getWhenLastModified")
    @WebResult(name = "getWhenLastModifiedResult", targetNamespace = "")
    @RequestWrapper(localName = "getWhenLastModified", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetWhenLastModified")
    @ResponseWrapper(localName = "getWhenLastModifiedResponse", targetNamespace = "http://www.mousephenotype.org/impress/soap/server", className = "org.mousephenotype.impress.GetWhenLastModifiedResponse")
    public String getWhenLastModified();

}
